configurable signature scheme + sr25519 support
Cerebellum-Network/ddc-client-kotlin pull request #24
Opened 2021-11-24 16:54 UTC by upalinski

2021-11-24 20:19 UTC, spoluyan approved these changes

2021-11-24 20:49 UTC, svalasovich requested changes
LGTM, just few minor comments

2021-11-24 20:49 UTC, svalasovich commented on src/main/kotlin/network/cere/ddc/client/common/signer/Ed25519Signer.kt
> +        Hex.decode(privateKey.removePrefix("0x")).sliceArray(0 until Ed25519.SECRET_KEY_SIZE)
Let use new constant HEX_PREFIX?

2021-11-24 20:49 UTC, svalasovich commented on src/main/kotlin/network/cere/ddc/client/common/signer/Ed25519Signer.kt
> +        return Hex.toHexString(signatureBytes)
Let use new extension toHex()?

2021-11-24 20:49 UTC, svalasovich commented on src/main/kotlin/network/cere/ddc/client/common/signer/Signer.kt
> +            Ed25519 -> Ed25519Signer(privateKey)
Probably It will be more readable move to new fabric method in enum Scheme for creating Signer?

2021-11-25 04:49 UTC, upalinski commented on src/main/kotlin/network/cere/ddc/client/common/signer/Ed25519Signer.kt
> +        return Hex.toHexString(signatureBytes)
done

2021-11-25 04:49 UTC, upalinski commented on src/main/kotlin/network/cere/ddc/client/common/signer/Ed25519Signer.kt
> +        Hex.decode(privateKey.removePrefix("0x")).sliceArray(0 until Ed25519.SECRET_KEY_SIZE)
done

2021-11-25 04:51 UTC, upalinski commented on src/main/kotlin/network/cere/ddc/client/common/signer/Signer.kt
> +            Ed25519 -> Ed25519Signer(privateKey)
as for me fabric method in Signer interface looks more readable than fabric method in enum. Any objections to left it as is?

2021-11-25 07:26 UTC, svalasovich commented on src/main/kotlin/network/cere/ddc/client/common/signer/Signer.kt
> +            Ed25519 -> Ed25519Signer(privateKey)
No, It's not principal position

2021-11-25 07:26 UTC, svalasovich approved these changes

2021-11-30 15:09 UTC, merged